name: Release qemu image

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/niki-on-github/vyos-qemu-images:dev
      options: --privileged -v /dev:/dev -v /tmp:/tmp
    steps:
      - name: Run docker entrypoint script
        run: |
          bash /entrypoint.sh

      - name: Setup variables
        id: vars
        run: |
          echo "tag-name=$(ls /tmp | grep 'qcow2' | head -n 1)" >> "$GITHUB_OUTPUT"
          mv -fv "/tmp/$(ls /tmp | grep 'qcow2' | head -n 1)" "/tmp/vyos-rolling-cloud-init.qcow2"
          echo "IMAGE_NAME=$(ls /tmp | grep 'qcow2' | head -n 1)" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.vars.outputs.tag-name }}"
          tag_exists_error: false
          message: "New rolling release"

      - name: Create release with artifact
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.vars.outputs.tag-name }}"
          artifacts: "/tmp/${{ env.IMAGE_NAME }}"
          artifactErrorsFailBuild: true
          body: |
            My rolling VyOS cloud init qemu images
